# Generated by Django 5.0.6 on 2024-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_start_time', models.TimeField()),
                ('task_end_time', models.TimeField()),
                ('task_date', models.DateTimeField()),
            ],
        ),
    ]
