# Generated by Django 5.0.6 on 2024-06-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_tasks_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_description',
            field=models.TextField(default='Task description Here.....'),
        ),
    ]
