# Generated by Django 5.0.6 on 2024-06-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_tasks_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
